package games.brennan.dungeontrain.mixin;

import com.mojang.logging.LogUtils;
import games.brennan.dungeontrain.worldgen.UpsideDownMirror;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.StructureManager;
import net.minecraft.world.level.WorldGenLevel;
import net.minecraft.world.level.chunk.ChunkAccess;
import net.minecraft.world.level.chunk.ChunkGenerator;
import org.slf4j.Logger;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Applies the upside-down band's vertical mirror to chunks generated by <b>Distant Horizons</b>, so the
 * far LOD terrain hangs the same way the loaded world does.
 *
 * <p>The band is not a world-gen hook — it is a post-generation mirror
 * ({@link UpsideDownMirror}) driven off the vanilla {@code SPAWN} chunk step
 * ({@link ChunkStatusSpawnMixin}) and NeoForge's {@code ChunkEvent.Load}
 * ({@code WorldUpsideDownEvents}). DH's distant generation reaches <em>neither</em>: it runs its own
 * pipeline (structures → biomes → noise → surface → features, then its own lighting bake), never goes
 * through {@code ChunkStatusTasks}, never reaches {@code SPAWN}, and fires no NeoForge chunk events. So
 * DH's LODs were the raw, right-way-up overworld while the chunks in front of the player were mirrored.
 * DT's other bands look correct under DH for the matching reason — void/erosion/chuncks live in
 * {@link NoiseBasedChunkGeneratorMixin} / {@link WorldGenRegionFloorMixin}, inside calls DH <em>does</em>
 * make.
 *
 * <p>DH's features step calls vanilla {@link ChunkGenerator#applyBiomeDecoration} with its own
 * {@code DhLitWorldGenRegion} (a real {@link net.minecraft.server.level.WorldGenRegion} wrapping the real
 * {@code ServerLevel}). That is the last terrain-writing vanilla call in DH's pipeline and it runs before
 * DH reads the chunk into LOD data, so mirroring at its {@code TAIL} lands in the LOD. The chunk here is
 * DH's own throwaway {@code ProtoChunk} — the server's real chunk still gets mirrored at Load exactly as
 * before, so there is no double-mirror.
 *
 * <p><b>Gate first, work second.</b> Everything is skipped unless the region belongs to DH; DH is not a
 * compile dependency (and shouldn't become one for this), so the check is on the region's class name,
 * memoised per class — the vanilla path pays one map lookup per decorated chunk. Inside,
 * {@link UpsideDownMirror#compute} self-gates and returns {@code null} when the band is off or the chunk
 * has no in-band column.
 *
 * <p>Best-effort, like the {@code SPAWN} precompute: any failure is logged and swallowed. The cost of a
 * failure here is a wrong-looking LOD, never broken world generation.
 *
 * <p>Known limits: DH LOD data already cached for a region stays upright until it regenerates; a DH
 * generation quality below "Features" never calls {@code applyBiomeDecoration} (DH's default does); and a
 * neighbour's feature spilling in after we mirror is left upright — invisible at LOD scale, and the
 * reason the vanilla path mirrors later, at {@code SPAWN}.
 */
@Mixin(ChunkGenerator.class)
public abstract class ChunkGeneratorDhLodMirrorMixin {

    private static final Logger LOGGER = LogUtils.getLogger();

    /** Package prefix of every Distant Horizons class, across DH 2.x jars and both loaders. */
    @Unique
    private static final String DH_PACKAGE_PREFIX = "com.seibel.";

    /**
     * "Is this world-gen region Distant Horizons'?", memoised per region class. Only a handful of region
     * classes ever exist in a run, so this stays tiny; concurrent because DH decorates on its own worker
     * threads alongside the vanilla worldgen workers.
     */
    @Unique
    private static final Map<Class<?>, Boolean> dungeontrain$dhRegionClasses = new ConcurrentHashMap<>();

    @Inject(method = "applyBiomeDecoration", at = @At("TAIL"))
    private void dungeontrain$mirrorDhLodChunk(
            WorldGenLevel level, ChunkAccess chunk, StructureManager structureManager, CallbackInfo ci) {
        try {
            if (!dungeontrain$isDistantHorizonsRegion(level)) return;
            if (!level.getLevel().dimension().equals(Level.OVERWORLD)) return; // band is overworld-only
            UpsideDownMirror.mirror(level.getLevel(), chunk);
        } catch (Throwable t) {
            // Never break generation — a DH LOD that renders upright is the worst outcome.
            LOGGER.error("[DungeonTrain] upside-down mirror failed on a Distant Horizons chunk at {}",
                    chunk.getPos(), t);
        }
    }

    @Unique
    private static boolean dungeontrain$isDistantHorizonsRegion(WorldGenLevel level) {
        return dungeontrain$dhRegionClasses.computeIfAbsent(
                level.getClass(), c -> c.getName().startsWith(DH_PACKAGE_PREFIX));
    }
}
