package games.brennan.dungeontrain.client.localization.edit;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.mojang.logging.LogUtils;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.packs.resources.Resource;
import net.minecraft.server.packs.resources.ResourceManager;
import org.slf4j.Logger;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * Which translation units are AI-authored and never human-reviewed, per locale — read from the
 * generated {@code assets/dungeontrain/localization_provenance/<locale>.json} manifests.
 *
 * <p>This is the data behind the translation editor's default filter. The full per-line
 * provenance lives repo-side under {@code localization/} and never ships; these manifests are
 * the compact shipped projection of it, regenerated by {@code stamp-provenance.py} and held in
 * lockstep by {@code check-provenance.py}. See {@code localization/README.md}.</p>
 *
 * <p>A body's value is either the string {@code "*"} (everything in it is AI-unreviewed — the
 * state 17 of the 19 locales are in, and why the manifests stay small) or an explicit list. A
 * body with no entry at all means "no provenance data", which reads as <b>nothing flagged</b>
 * rather than everything: over-flagging would send a translator to re-check text a human already
 * signed off on.</p>
 *
 * <p>Loaded through the <b>client</b> resource pipeline like
 * {@link games.brennan.dungeontrain.client.localization.LocalizationCreditRegistry}, so it is
 * populated at the title screen where no world is loaded.</p>
 */
public final class ProvenanceManifestRegistry {

    private static final Logger LOGGER = LogUtils.getLogger();

    private static final String DIR = "localization_provenance";
    private static final String JSON_EXT = ".json";
    /** Marker meaning "every unit in this body". Must match {@code provenance_io.MANIFEST_ALL}. */
    private static final String ALL = "*";

    /** locale -> namespace -> flagged lang keys ({@code null} value = the {@code "*"} marker). */
    private static final Map<String, Map<String, Set<String>>> LANG = new HashMap<>();
    /** locale -> flagged book paths ({@code null} = the {@code "*"} marker, i.e. every book). */
    private static final Map<String, Set<String>> BOOKS = new HashMap<>();

    private ProvenanceManifestRegistry() {}

    /** Reload from the given client {@link ResourceManager} (bundled + resource-pack overrides). */
    public static synchronized void load(ResourceManager resourceManager) {
        LANG.clear();
        BOOKS.clear();
        int loaded = 0;
        int failed = 0;
        Map<ResourceLocation, Resource> resources =
            resourceManager.listResources(DIR, rl -> rl.getPath().endsWith(JSON_EXT));
        for (Map.Entry<ResourceLocation, Resource> entry : resources.entrySet()) {
            try (InputStream in = entry.getValue().open()) {
                if (parse(in)) {
                    loaded++;
                } else {
                    failed++;
                }
            } catch (Exception e) {
                LOGGER.error("[DungeonTrain] ProvenanceManifest: failed to read {} — {}",
                    entry.getKey(), e.toString());
                failed++;
            }
        }
        LOGGER.info("[DungeonTrain] ProvenanceManifest loaded — {} locale(s) (failed: {})",
            loaded, failed);
    }

    public static synchronized void clear() {
        LANG.clear();
        BOOKS.clear();
    }

    public static synchronized int count() {
        return LANG.size();
    }

    /**
     * Whether {@code key} in {@code namespace} is machine-translated with no human review.
     *
     * <p>False when the locale ships no manifest, so a third-party localization pack — which
     * has provenance nobody here tracked — never gets its work labelled as AI output.</p>
     */
    public static synchronized boolean isAiUnreviewedLang(String locale, String namespace, String key) {
        Map<String, Set<String>> byNamespace = LANG.get(normalize(locale));
        if (byNamespace == null || !byNamespace.containsKey(namespace)) {
            return false;
        }
        Set<String> flagged = byNamespace.get(namespace);
        return flagged == null || flagged.contains(key); // null = the "*" whole-body marker
    }

    /** Whether the book at {@code bookPath} (e.g. {@code random_books/deathnote}) is AI-unreviewed. */
    public static synchronized boolean isAiUnreviewedBook(String locale, String bookPath) {
        String code = normalize(locale);
        if (!BOOKS.containsKey(code)) {
            return false;
        }
        Set<String> flagged = BOOKS.get(code);
        return flagged == null || flagged.contains(bookPath);
    }

    /** Whether any manifest at all was loaded for {@code locale}. */
    public static synchronized boolean hasData(String locale) {
        return LANG.containsKey(normalize(locale));
    }

    /**
     * Parse one manifest into the registry. Returns false (and logs) on a shape we don't
     * recognise — a bad manifest costs the editor its filter, never its ability to open.
     */
    private static boolean parse(InputStream in) {
        JsonElement rootEl = JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8));
        if (!rootEl.isJsonObject()) {
            LOGGER.error("[DungeonTrain] ProvenanceManifest: root is not a JSON object");
            return false;
        }
        JsonObject root = rootEl.getAsJsonObject();
        if (!root.has("locale") || !root.get("locale").isJsonPrimitive()) {
            LOGGER.error("[DungeonTrain] ProvenanceManifest: missing 'locale'");
            return false;
        }
        String locale = normalize(root.get("locale").getAsString());
        if (locale.isEmpty()) {
            return false;
        }

        Map<String, Set<String>> byNamespace = new HashMap<>();
        if (root.has("lang") && root.get("lang").isJsonObject()) {
            for (Map.Entry<String, JsonElement> e : root.getAsJsonObject("lang").entrySet()) {
                byNamespace.put(e.getKey(), flagsOf(e.getValue()));
            }
        }
        LANG.put(locale, byNamespace);

        if (root.has("books")) {
            BOOKS.put(locale, flagsOf(root.get("books")));
        }
        return true;
    }

    /** A body's flagged set, or {@code null} for the {@code "*"} whole-body marker. */
    private static Set<String> flagsOf(JsonElement value) {
        if (isAll(value)) {
            return null;
        }
        Set<String> out = new HashSet<>();
        if (value != null && value.isJsonArray()) {
            for (JsonElement el : value.getAsJsonArray()) {
                if (el.isJsonPrimitive() && el.getAsJsonPrimitive().isString()) {
                    out.add(el.getAsString());
                }
            }
        }
        return out;
    }

    private static boolean isAll(JsonElement value) {
        return value != null && value.isJsonPrimitive() && value.getAsJsonPrimitive().isString()
            && ALL.equals(value.getAsString());
    }

    private static String normalize(String locale) {
        return locale == null ? "" : locale.toLowerCase(java.util.Locale.ROOT);
    }
}
