package games.brennan.dungeontrain.client.shaders;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.mojang.logging.LogUtils;
import net.minecraft.resources.ResourceLocation;
import org.slf4j.Logger;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * One officially supported Iris shader pack, as listed in {@code shader_menu/packs.json}.
 *
 * <p>The nine packs are the ones measured to load and behave correctly under Dungeon Train's band
 * and carriage atmosphere systems — see {@code docs/shaders/compat-matrix.md}. The manifest is
 * generated by {@code scripts/shaders/fetch-packs.py} against the Modrinth API rather than typed by
 * hand, so the pinned build, its size and its hash cannot drift apart from each other.</p>
 *
 * <p><b>Read off the classpath, not through the resource manager.</b> Every entry carries a URL the
 * game will fetch and a hash it will trust; a resource pack able to override this file would be able
 * to point the download button anywhere. It is also read before any resource reload has happened,
 * since the page opens from the title screen.</p>
 *
 * @param id        ours, stable across a pack renaming itself; keys the preview texture
 * @param name      display name
 * @param version   the pinned build, as the pack numbers it
 * @param author    pack author(s), from the Modrinth project's owner
 * @param filename  the zip's name, and therefore its name in {@code shaderpacks/}
 * @param url       the author's own Modrinth CDN link — nothing is mirrored or bundled
 * @param sha512    checked after download; a mismatch means the file is discarded
 * @param size      bytes, for the progress bar and the "how big is this" line
 * @param page      the Modrinth project page, offered when a download fails
 * @param performance what this costs to run — see {@link Performance}
 * @param vanillaRank 1 = closest to vanilla, 9 = furthest; the two style sort orders read this
 *                    list from either end
 */
public record ShaderPack(String id, String name, String version, String author, String filename,
                         String url, String sha512, long size, String page,
                         Performance performance, int vanillaRank) {

    /**
     * Roughly what a pack costs to run, cheapest first.
     *
     * <p><b>Curated, not benchmarked.</b> Measuring it off the capture run does not work — that
     * client is frame-capped, so all nine packs rendered within 10 frames of each other and the
     * numbers meant nothing. A real figure needs an uncapped frame-time harness. Until that exists,
     * a tier a player can act on beats a number that looks measured and is not, and the tiers are
     * what each pack is openly for: MakeUp is called Ultra Fast because that is its design.</p>
     */
    public enum Performance {
        VERY_LIGHT("very-light"),
        LIGHT("light"),
        MODERATE("moderate"),
        HEAVY("heavy");

        private final String id;

        Performance(String id) {
            this.id = id;
        }

        static Performance of(String raw) {
            for (Performance value : values()) {
                if (value.id.equals(raw)) {
                    return value;
                }
            }
            return MODERATE;
        }

        /** e.g. {@code gui.dungeontrain.shaders.perf.very_light}. */
        public String key() {
            return "gui.dungeontrain.shaders.perf." + name().toLowerCase(java.util.Locale.ROOT);
        }
    }

    /** How the list may be ordered. The button above it cycles these. */
    public enum Sort {
        /** Manifest order — what the page opens on. */
        DEFAULT("default", null),
        /** Cheapest to run first. */
        PERFORMANCE("performance",
                java.util.Comparator.comparingInt((ShaderPack p) -> p.performance().ordinal())
                        .thenComparingInt(ShaderPack::vanillaRank)),
        /** Closest to vanilla first. */
        VANILLA("vanilla", java.util.Comparator.comparingInt(ShaderPack::vanillaRank)),
        /** Furthest from vanilla first — the same list read backwards. */
        FANCY("fancy", java.util.Comparator.comparingInt(ShaderPack::vanillaRank).reversed());

        private final String id;
        private final java.util.Comparator<ShaderPack> order;

        Sort(String id, java.util.Comparator<ShaderPack> order) {
            this.id = id;
            this.order = order;
        }

        public Sort next() {
            return values()[(ordinal() + 1) % values().length];
        }

        /** e.g. {@code gui.dungeontrain.shaders.sort.vanilla}. */
        public String key() {
            return "gui.dungeontrain.shaders.sort." + id;
        }

        /** The packs in this order. {@link #DEFAULT} keeps the manifest's own. */
        public List<ShaderPack> apply(List<ShaderPack> packs) {
            if (order == null) {
                return packs;
            }
            List<ShaderPack> sorted = new ArrayList<>(packs);
            sorted.sort(order);
            return List.copyOf(sorted);
        }
    }

    private static final Logger LOGGER = LogUtils.getLogger();

    private static final String MANIFEST = "/assets/dungeontrain/shader_menu/packs.json";

    /** The only host a pack may be fetched from. See {@link ShaderPackDownloader}. */
    static final String ALLOWED_HOST = "cdn.modrinth.com";

    private static List<ShaderPack> cached;

    /** The supported packs in manifest order, or an empty list if the manifest will not load. */
    public static List<ShaderPack> all() {
        if (cached != null) {
            return cached;
        }
        cached = load();
        return cached;
    }

    /** The preview screenshot: the same scene, camera and time of day for every pack. */
    public ResourceLocation preview() {
        return ResourceLocation.fromNamespaceAndPath("dungeontrain", "textures/gui/shaders/" + id + ".png");
    }

    /** e.g. {@code "1.1 MB"} — the size next to the download button. */
    public String sizeLabel() {
        return size >= 1024L * 1024L
                ? String.format("%.1f MB", size / (1024.0 * 1024.0))
                : Math.max(1L, size / 1024L) + " KB";
    }

    private static List<ShaderPack> load() {
        List<ShaderPack> packs = new ArrayList<>();
        try (InputStream in = ShaderPack.class.getResourceAsStream(MANIFEST)) {
            if (in == null) {
                LOGGER.error("[DungeonTrain] Shader manifest {} is missing from the jar", MANIFEST);
                return List.of();
            }
            JsonObject root = JsonParser.parseReader(
                    new InputStreamReader(in, StandardCharsets.UTF_8)).getAsJsonObject();
            JsonArray array = root.getAsJsonArray("packs");
            for (int i = 0; i < array.size(); i++) {
                ShaderPack pack = read(array.get(i).getAsJsonObject());
                if (pack != null) {
                    packs.add(pack);
                }
            }
        } catch (Exception e) {
            LOGGER.error("[DungeonTrain] Could not read the shader manifest: {}", e.toString());
            return List.of();
        }
        LOGGER.info("[DungeonTrain] Shader menu: {} supported packs", packs.size());
        return List.copyOf(packs);
    }

    /**
     * One entry, or {@code null} if it is malformed or points somewhere it should not.
     *
     * <p>The host check is here rather than at the download so a bad entry is absent from the page
     * entirely — a button that cannot work is worse than no button.</p>
     */
    private static ShaderPack read(JsonObject o) {
        try {
            String url = o.get("url").getAsString();
            if (!url.startsWith("https://" + ALLOWED_HOST + "/")) {
                LOGGER.error("[DungeonTrain] Shader manifest entry {} points off {} — dropped",
                        o.get("id"), ALLOWED_HOST);
                return null;
            }
            return new ShaderPack(
                    o.get("id").getAsString(),
                    o.get("name").getAsString(),
                    o.get("version").getAsString(),
                    o.get("author").getAsString(),
                    o.get("filename").getAsString(),
                    url,
                    o.get("sha512").getAsString(),
                    o.get("size").getAsLong(),
                    o.get("page").getAsString(),
                    Performance.of(o.get("performance").getAsString()),
                    o.get("vanilla_rank").getAsInt());
        } catch (Exception e) {
            LOGGER.error("[DungeonTrain] Malformed shader manifest entry: {}", e.toString());
            return null;
        }
    }
}
