version=${mod_version}
branch=${git_branch}
dev_hours=${dev_hours}
updates_count=${updates_count}
updates_window_months=${updates_window_months}
updates_month=${updates_month}
updates_week=${updates_week}
updates_day=${updates_day}
updates_year=${updates_year}
last_update_date=${last_update_date}
