#!/usr/bin/env python3
"""
Collect the set of clock hours in which Dungeon Train work was committed, across every
repo the project spans, and write the snapshot the build bakes into the jar.

The unit is a **clock hour, not a commit and not a repo-hour**: an hour in which commits
landed in dungeon-train-mc *and* playermob-mc *and* dp-relay is ONE hour. Everything here
therefore works on a set of hour buckets and unions them — nothing ever adds two counts
together. (Naively summing per-repo counts overstates the total by ~30%.)

Every commit counts, bots included: the auto-release cascade's commits are the tail of
release work that was itself done by hand.

Why a committed snapshot instead of computing this at build time: the sibling repos are
not present when Dungeon Train builds — not in CI, not on another machine. So this script
runs locally and commits its output, and build.gradle unions that snapshot with the LIVE
git history of the Dungeon Train checkout. DT's own hours are therefore always current
without re-running anything; the siblings' hours are as fresh as the last run of this
script. Re-run it before a real release.

Usage:  python3 scripts/dev-hours/collect.py [--config PATH] [--out PATH] [--dry-run]
"""
import argparse
import json
import os
import subprocess
import sys
import time
import calendar
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DEFAULT_CONFIG = REPO / "scripts/dev-hours/repos.json"
DEFAULT_OUT = REPO / "docs/dev-hours/hour-index.json"
SCHEMA_VERSION = "1.0"

# `%ad` is the AUTHOR date in the author's own timezone — the wall clock the work actually
# happened on, which is what "hours put in" means. The bucket string is then read back as if
# it were UTC purely to get a stable integer key; no timezone maths is intended or wanted.
HOUR_FORMAT = "%Y-%m-%dT%H"
GIT_LOG = ["git", "log", "--all", "--pretty=%ad", f"--date=format:{HOUR_FORMAT}"]


def hour_key(stamp):
    """``2026-08-26T14`` -> epoch-hour int. Returns None for anything unparseable."""
    try:
        return calendar.timegm(time.strptime(stamp.strip(), HOUR_FORMAT)) // 3600
    except (ValueError, AttributeError):
        return None


def hours_from_lines(lines):
    """Set of epoch-hour ints from ``git log`` output lines. Blank/garbage lines are dropped."""
    keys = (hour_key(line) for line in lines)
    return {k for k in keys if k is not None}


def delta_encode(hours):
    """Sorted hour set -> [first, gap, gap, …]. Keeps the committed index small and diffable."""
    ordered = sorted(hours)
    if not ordered:
        return []
    out = [ordered[0]]
    out.extend(b - a for a, b in zip(ordered, ordered[1:]))
    return out


def delta_decode(encoded):
    """Inverse of :func:`delta_encode`."""
    out = []
    running = 0
    for i, step in enumerate(encoded):
        running = step if i == 0 else running + step
        out.append(running)
    return out


def _git(args, cwd):
    return subprocess.run(
        args, cwd=cwd, check=True, timeout=120,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
    ).stdout


def collect_repo(name, path):
    """Read one repo's hour set. Returns (hours, last_commit_date, error_or_None)."""
    root = Path(os.path.expanduser(path))
    if not (root / ".git").exists():
        return set(), None, f"not a git repository: {root}"
    try:
        hours = hours_from_lines(_git(GIT_LOG, root).splitlines())
        last = _git(["git", "log", "--all", "-1", "--pretty=%ad", "--date=short"], root).strip()
        return hours, (last or None), None
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, OSError) as exc:
        # A repo we can't read is a gap in the number, not a reason to fail the run — this
        # script has to work on a machine that only has Dungeon Train checked out.
        return set(), None, f"git failed: {exc}"


def build_index(config):
    """Union every configured repo's hours into the index document."""
    union = set()
    repos = []
    for entry in config["repos"]:
        name, path = entry["name"], entry["path"]
        hours, last, error = collect_repo(name, path)
        if error:
            print(f"WARNING: skipping {name} — {error}", file=sys.stderr)
        union |= hours
        repos.append({
            "name": name,
            "hours": len(hours),
            "lastCommit": last,
            "skipped": bool(error),
        })
    return {
        "comment": "GENERATED by scripts/dev-hours/collect.py — do not hand-edit. "
                   "Union of the clock hours in which any Dungeon Train repo saw a commit; "
                   "overlapping hours count once. `hours` is delta-encoded epoch hours.",
        "schemaVersion": SCHEMA_VERSION,
        "generatedAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "totalHours": len(union),
        "repos": repos,
        "hours": delta_encode(union),
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--dry-run", action="store_true", help="report the totals, write nothing")
    args = ap.parse_args(argv)

    config = json.loads(args.config.read_text(encoding="utf-8"))
    index = build_index(config)

    naive_sum = sum(r["hours"] for r in index["repos"])
    for r in index["repos"]:
        mark = " (skipped)" if r["skipped"] else ""
        print(f"  {r['name']:<28} {r['hours']:>5} hours   last {r['lastCommit'] or '—'}{mark}")
    print(f"  {'UNION (overlaps count once)':<28} {index['totalHours']:>5} hours"
          f"   [{naive_sum - index['totalHours']} double-counted hours removed]")

    if args.dry_run:
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(index, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {args.out.relative_to(REPO) if args.out.is_relative_to(REPO) else args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
